version: '3.4'

services:
  nginx:
    container_name: "tourism-demo-nginx"
    image: nginx:alpine
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./docker/log/nginx:/var/log/nginx:rw
      - ./public:/var/www/app/public:delegated
    ports:
      - "80:80"

  php:
    container_name: "tourism-demo-php"
    build:
      context: docker/php
      dockerfile: Dockerfile
    user: "1000:1000"
    volumes:
      - .:/var/www/app:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/without-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/without-blackfire.ini:/usr/local/etc/php/conf.d/blackfire.ini
    working_dir: /var/www/app
    environment:
      - PHP_IDE_CONFIG=serverName=tourism-demo.loc
      - XDEBUG_CONFIG=remote_enable=true remote_host=172.17.0.1

    ports:
      - "8707:8707"

  postgresql:
    container_name: "tourism-demo-postgres"
    restart: on-failure
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tourism_demo_db
    volumes:
      - postgresql-data:/var/lib/postgresql

volumes:
  postgresql-data:
