<?php


namespace App\Services\ContentRelevantService\RelevantHandlers;

use App\Models\Place;

/**
 * Class RatingHandler
 * @package App\Services\ContentRelevantService\RelevantHandlers
 */
class RatingHandler extends AbstractRelevantHandler implements Handler
{
    /**
     * @var
     */
    private $item;

    /**
     * RatingHandler constructor.
     * @param $item
     */
    public function __construct($item)
    {
        $this->item = $item;
    }

    /**
     * @param int $sum
     * @param $model_class
     * @return int|null
     */
    public function handle(int $sum, $model_class): ?int
    {
        if ($model_class === Place::class) {
            if ($rating_instance = $this->item->rating()->first()) {
                $rating = $rating_instance->value;

                switch ($rating) {
                    case 1:
                        $sum *= 0.5;
                        break;
                    case 2:
                        $sum *= 0.7;
                        break;
                    case 3:
                        $sum *= 0.8;
                        break;
                    case 4:
                        $sum *= 0.9;
                        break;
                    case 5:
                        $sum *= 1;
                        break;
                    default:
                        break;
                }
            }
        }
        return parent::handle($sum, $model_class); // TODO: Change the autogenerated stub
    }
}
